(* ::Package:: *)
(* Tangency (fold) case:  I (w + (b/2) s^2) g - nu g'' = 1.
   Exact solution by the Mehler (Gaussian propagator) ansatz:
     g(s) = Int_0^oo dt f(t) Exp[-I w t - alpha(t) s^2/2],
     alpha(t) = as Tanh[be t],  f(t) = Sech[be t]^(1/2),
     as = Sqrt[I b/(2 nu)],  be = Sqrt[2 I nu b].
   Yields the closed-form absorption at the fold (w = 0)
     A = Cf |S|^2 b^(-3/4) nu^(-1/4),   Cf = Sqrt[2 Pi] Is Cos[3 Pi/8] 2^(-1/4),
     Is = Int_0^oo Sinh[t]^(-1/2) dt = Gamma[1/4]^2/(2 Sqrt[Pi]),
   the nu^(1/4) layer width, and the universal fold kernel K(W).
   Run:  math -script 04_tangency_mehler.wl *)

Print["=== 04 tangency: Mehler solution, nu^(-1/4) fold weight ==="];

(* 1) the ansatz solves the initial-value problem symbolically ----------- *)
as = Sqrt[I b/(2 nu)];
be = Sqrt[2 I nu b];
alpha[t_] := as Tanh[be t];
f[t_] := Sech[be t]^(1/2);
u[s_, t_] := f[t] Exp[-I w t - alpha[t] s^2/2];

resid = Simplify[
  D[u[s, t], t] + I (w + b s^2/2) u[s, t] - nu D[u[s, t], {s, 2}],
  Assumptions -> {nu > 0, b > 0, t > 0}];
Print["propagator residual (must be 0): ", resid];
Print["initial condition u(s,0) = ", Simplify[u[s, 0]]];
Print["so g = Int_0^oo u dt gives (I(w + b s^2/2) - nu d^2/ds^2) g = 1"];

(* 2) closed-form absorption at the fold, w = 0 --------------------------- *)
(* Int Exp[-alpha s^2/2] ds = Sqrt[2 Pi/alpha]; the integrand collapses to
   Sqrt[2 Pi/as] Sinh[be t]^(-1/2); rotating t = tau/be gives Is.
   Along the ray arg(z) = Pi/4 the phase of Sinh[z] winds, so the principal
   Sqrt branch jumps; use the continuous branch valid for Re[z] > 0:
     Sinh[z]^(-1/2) = Sqrt[2] Exp[-z/2] (1 - Exp[-2 z])^(-1/2).            *)
sinhInvSqrt[z_] := Sqrt[2] Exp[-z/2]/Sqrt[1 - Exp[-2 z]];

Is = Integrate[1/Sqrt[Sinh[tau]], {tau, 0, Infinity}];
Print["Is = Int_0^oo Sinh^(-1/2) = ", Is];
IsGamma = Gamma[1/4]^2/(2 Sqrt[Pi]);
Print["equals Gamma[1/4]^2/(2 Sqrt[Pi]): ",
  Simplify[N[Is, 30] == N[IsGamma, 30]], "  = ", N[IsGamma, 10]];

(* Sqrt[2Pi/as]/be * Is picks up the phase Exp[-3 Pi I/8]; A = Re[...].    *)
Cf = Sqrt[2 Pi] IsGamma Cos[3 Pi/8] 2^(-1/4) // FullSimplify;
Print["A(w=0) = Cf b^(-3/4) nu^(-1/4),   Cf = ", Cf, " = ", N[Cf, 10]];

(* independent numeric check of the unrotated t-integral at nu = b = 1     *)
Anum = Re[Sqrt[2 Pi/(as /. {nu -> 1, b -> 1})] NIntegrate[
   sinhInvSqrt[(be /. {nu -> 1, b -> 1}) t], {t, 0, Infinity},
   AccuracyGoal -> 10]];
Print["numeric A(nu=1, b=1) = ", Anum, "  vs Cf = ", N[Cf, 10]];

(* 3) layer width -------------------------------------------------------- *)
Print["balance (b/2) Delta^2 = nu/Delta^2  ->  Delta = (2 nu/b)^(1/4)"];
Print["width exponent 1/4"];

(* 4) universal fold kernel K(W), W = w/Sqrt[2 nu b] ---------------------- *)
KW[W_?NumericQ] := Re[E^(-I Pi/8) NIntegrate[
    Exp[-I W tau] sinhInvSqrt[tau E^(I Pi/4)], {tau, 0, Infinity},
    AccuracyGoal -> 8, MaxRecursion -> 14]];
K0 = IsGamma Cos[3 Pi/8];
Print["K(0) = Is Cos[3Pi/8] = ", N[K0, 10], "  check: ", KW[0]];
Print["collisionless asymptote K(W -> -oo) = Sqrt[Pi/|W|]:"];
Do[Print["  K(", W, ") = ", KW[W], "  vs ", N[Sqrt[Pi/Abs[W]], 8]],
  {W, {-10, -30, -100}}];
Print["decay on the rootless side: K(10) = ", KW[10],
  ", K(30) = ", KW[30]];

(* 5) export thesis macros ------------------------------------------------ *)
Export["../thesis/tex/fold-constants.tex",
  StringJoin[
    "% generated by symbolic/04_tangency_mehler.wl - do not edit\n",
    "\\newcommand{\\FoldIs}{", ToString[N[IsGamma, 6]], "}\n",
    "\\newcommand{\\FoldCf}{", ToString[N[Cf, 6]], "}\n",
    "\\newcommand{\\FoldKzero}{", ToString[N[K0, 6]], "}\n"],
  "Text"];

Export["../data/mathematica_04.txt",
  StringJoin[
    "propagator residual = ", ToString[resid, InputForm], "\n",
    "Is = Gamma[1/4]^2/(2 Sqrt[Pi]) = ", ToString[N[IsGamma, 12]], "\n",
    "A(w=0) = Cf b^(-3/4) nu^(-1/4), Cf = ", ToString[N[Cf, 12]], "\n",
    "numeric t-integral check (nu=b=1): ", ToString[Anum], "\n",
    "K(0) = ", ToString[N[K0, 12]], "\n",
    "K(-30) = ", ToString[KW[-30]], " vs Sqrt[Pi/30] = ",
    ToString[N[Sqrt[Pi/30], 8]], "\n",
    "width Delta = (2 nu/b)^(1/4)\n"],
  "Text"];
Print["written ../data/mathematica_04.txt and ../thesis/tex/fold-constants.tex"];
Exit[];
