ClearAll["Global`*"];

out = OpenWrite["tex/symbolic-results.tex"];

writeTex[name_, expr_] := WriteString[
    out,
    "\\newcommand{\\" <> name <> "}{" <> ToString[TeXForm[expr]] <> "}\n"
];

writeLine[text_] := WriteString[out, text <> "\n"];

thetaRule = Derivative[1][thetaB][t] -> omegaB;
phiRule = Derivative[1][phiSlow][t] -> q omegaB deltaTP + OmegaT;
phase = m2 thetaB[t] + n phiSlow[t];
omegaRes = FullSimplify[D[phase, t] /. {thetaRule, phiRule}];

writeLine["% Generated by mathematica/derive_layer.wls"];
writeTex["SymbolicPhaseDerivative", omegaRes];

omegaToy[eta_] = alpha + beta eta + gamma eta^2;
roots = FullSimplify[eta /. Solve[omegaToy[eta] == 0, eta]];
jacobianWeights = FullSimplify[1/Abs[D[omegaToy[eta], eta] /. eta -> #] & /@ roots];

writeTex["QuadraticResonanceRoots", roots];
writeTex["QuadraticJacobianWeights", jacobianWeights];

interiorEquation =
    I a (eta - eta0) g[eta] - nu Derivative[2][g][eta] == S[eta];
scaledInterior = FullSimplify[
    interiorEquation /. {
        eta -> eta0 + delta x,
        Derivative[2][g][eta] -> Derivative[2][G][x]/delta^2,
        g[eta] -> G[x],
        S[eta] -> S0
    } /. delta -> (nu/a)^(1/3),
    Assumptions -> {a > 0, nu > 0}
];

writeTex["InteriorScaledEquation", scaledInterior];
writeTex["InteriorLayerWidth", (nu/Abs[Derivative[1][Omega][eta0]])^(1/3)];

k = Sqrt[I OmegaE/nu];
gBoundary[eta_] = 1/(I OmegaE) (1 - Cosh[k (1 - eta)]/Cosh[k]);
aBoundary = FullSimplify[
    Integrate[gBoundary[eta], {eta, 0, 1}],
    Assumptions -> {OmegaE > 0, nu > 0}
];
realSmallNuBoundary = Sqrt[nu]/(Sqrt[2] OmegaE^(3/2));

writeTex["BoundaryExactResponse", gBoundary[eta]];
writeTex["BoundaryIntegratedResponse", aBoundary];
writeTex["BoundarySmallNuRealAbsorption", realSmallNuBoundary];
writeTex["BoundaryLayerWidth", Sqrt[nu/OmegaE]];

Close[out];

Print["wrote tex/symbolic-results.tex"];
